theme: jekyll-theme-minimal
title: Asahi Ushio
description: AI Researcher based on Tokyo/Japan
logo: /assets/img/peofile.png
description: Minimal is a theme for GitHub Pages.
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal